arcanjo/urls.py
from django.urls import path
from arcanjo import views

app_name = 'arcanjo'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('search/', views.search, name='search'),

    # CRUD
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    # CRUD - User
    path('user/create/', views.register, name='register'),
    path('', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('arcanjo.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls),
]

# Configuração para envio de arquivo para o servidor
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

arcanjo/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    # Retorna o nome da categoria dentro de category no admin do django
    def __str__(self) -> str:
        return f'{self.name}'


# Isso seria uma "tabela" chamada Contact
class Contact(models.Model):
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    phone = models.CharField(max_length=80)
    email = models.EmailField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    # Retorna o nome do contato dentro de contacts no admin do django
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

arcanjo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models
from django.contrib.auth import password_validation


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(label='Primeiro Nome')
    last_name = forms.CharField(label='Segundo Nome')
    phone = forms.CharField(label='Telefone')
    email = forms.EmailField(label='E-mail')
    picture = forms.ImageField(
        label='Imagem',
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*'
            }
        )
    )

    class Meta:
        model = models.Contact
        fields = ('first_name', 'last_name', 'phone', 'email', 'description', 'category', 'picture',)

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )
            # self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':
            self.add_error(
                'first_name',
                ValidationError(
                    'Veio do add_error',
                    code='invalid'
                )
            )

        return first_name


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(required=True, label='Primeiro Nome')
    last_name = forms.CharField(required=True, label='Segundo Nome')

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )


class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        label="Primeiro Nome",
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        label="Segundo Nome",
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

arcanjo/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(
        request, 'arcanjo/index.html',
    )

arcanjo/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from arcanjo.forms import ContactForm
from arcanjo.models import Contact


def create(request):
    form_action = reverse('arcanjo:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            print("Formulário é válido!")
            contact = form.save()
            return redirect('arcanjo:update', contact_id=contact.pk)

        # print(contacts.query)
        return render(request, 'contact/create.html', context)

    context = {
        'form': ContactForm(),
        'form_action': form_action,

    }
    # print(contacts.query)
    return render(request, 'contact/create.html', context)


def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    form_action = reverse('arcanjo:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            print("Formulário é válido!")
            contact = form.save()
            return redirect('arcanjo:update', contact_id=contact.pk)

        # print(contacts.query)
        return render(request, 'contact/create.html', context)

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,

    }
    # print(contacts.query)
    return render(request, 'contact/create.html', context)


def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('arcanjo:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )

arcanjo/views/contact_view.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from arcanjo.models import Contact
from django.core.paginator import Paginator


def index(request):
    '''seleciona todos os contatos onde o campo show for true e
    mostrar em ordem decrescente'''
    contacts = Contact.objects.filter(show=True).order_by('-id')

    paginator = Paginator(contacts, 12)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'site_title': 'Contatos - '}

    # print(contacts.query)
    return render(request, 'contact/index.html', context)


def search(request):
    '''realiza a busca do contato'''
    search_value = request.GET.get('q', '').strip()
    # print('search_value: ', search_value)
    if search_value == '':
        return redirect('arcanjo:index')

    contacts = Contact.objects. \
        filter(show=True). \
        filter(Q(first_name__icontains=search_value) |
               Q(last_name__icontains=search_value) |
               Q(phone__icontains=search_value) |
               Q(email__icontains=search_value)) \
        .order_by('-id')
    # print(contacts.query)

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'site_title': 'Contatos - '}
    # print(contacts.query)

    return render(request, 'contact/index.html', context)


def contact(request, contact_id):
    '''retorna os dados de um contato via id (pk),
    caso o id não seja encontrado, ele retorna 404'''
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    site_title = f'{single_contact.first_name} {single_contact.last_name} - '
    context = {'contact': single_contact, 'site_title': site_title}

    # print(single_contact.query)
    return render(request, 'contact/contact.html', context)

arcanjo/views/user_forms.py
from django.shortcuts import render, redirect
from arcanjo.forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth


def register(request):
    form = RegisterForm()

    # messages.info(request, 'Mensagem de Informação!')

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário Registrado!')
            return redirect('arcanjo:login')

    context = {'form': form}

    return render(request, 'contact/register.html', context)


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso!')
            return redirect('arcanjo:index')
        messages.error(request, 'Login inválido!')

    context = {'form': form}
    return render(request, 'contact/login.html', context)


def logout_view(request):
    auth.logout(request)
    return redirect('arcanjo:login')


def user_update(request):
    form = RegisterUpdateForm(instance=request.user)
    if request.method != "POST":
        return render(request, 'contact/update-user.html', {'form': form})

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(request, 'contact/update-user.html', {'form': form})
    form.save()
    return redirect("arcanjo:user_update")

arcanjo/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ contact.first_name }} {{ contact.last_name }}</h1>
        <a href="{% url 'arcanjo:index' %}" class="btn btn-primary">Voltar</a>
      </div>      

        <p><b>ID: </b> {{ contact.id }}</p>
        <p><b>Email: </b> {{ contact.email }}</p>
        <p><b>Celular: </b> {{ contact.phone }}</p>
        <p><b>Data de Criação: </b> {{ contact.created_date }}</p>
        <p><b>Descrição: </b> {{ contact.description }}</p>
        <p><b>Categoria: </b> {{ contact.category.name }}</p>

        {% if contact.picture %}
          <p>
            <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}">
          </p>
        {% endif %}

        <div class="d-grid gap-2 col-6 mx-auto">
          <a class="btn btn-primary" href="{% url 'arcanjo:update' contact.id %}">Update</a></button>      
          <a class="btn btn-danger" href="{% url 'arcanjo:delete' contact.id %}">Delete</a></button>  

          <form action="{% url 'arcanjo:delete' contact.id %}" method="POST">
            {% csrf_token %}
            <br>
            {% if confirmation == 'no' %}
              <input type="hidden" name="confirmation" value="yes">
              <button class="btn btn-outline-warning d-grid gap-2 col-6 mx-auto" type="submit">Confirma?</button>
            {% endif %}
          </form>
          <br>
        </div>
    </div>
{% endblock content %}

arcanjo/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard - Criar Contato</h1>
            <a href="{% url 'arcanjo:index' %}" class="btn btn-primary">Voltar</a>
        </div>

        <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        
                        {{ field.errors }}
                    </div>
                    
                    {% comment %} Exibição da Imagem {% endcomment %}
                    {% if field.name == 'picture' and field.value.url %}
                        <div class="form-group">
                            <img src="{{ field.value.url }}" alt="">
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">Enviar</button>
            </div>
            <br>
        </form>
    </div>
{% endblock content %}

arcanjo/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  
  <h1 class="h2">Dashboard - Contatos</h1>
  {% if user.is_authenticated %}
    <a href="{% url 'arcanjo:create' %}" class="btn btn-primary">Criar contato</a>
  {% endif %}

</div>

<div class="table-responsive">
  <table class="table table-hover">
    <caption>Lista de usuários</caption>
    <thead>
      <tr class="table-secondary">
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Sobrenome</th>
        <th scope="col">Telefone</th>
        <th scope="col">E-mail</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in page_obj %}
      <tr>
        <td><a class="table-link" href="{% url 'arcanjo:contact' contact.id %}">
          {{ contact.id }}
        </a>
      </td>
      <td class="table-cel">
        {{ contact.first_name }}
      </td>
      <td class="table-cel">
        {{ contact.last_name }}
      </td>
      <td class="table-cel">
        {{ contact.phone }}
      </td>
      <td class="table-cel">
        {{ contact.email }}
      </td>
      {% endfor %}
      </tr>
    </tbody>
  </table>
</div>
{% else %}
  <br>
  <div class="single-contact">
    <h1 class="single-contact-name">
      Nenhum contato encontrado!
    </h1>
  </div>
{% endif %}
{% endblock content %}

arcanjo/templates/contact/login.html
{% extends "global/login.html" %}

{% block content %}
    <div class="form-wrapper">
        <br>
        {% if user.is_authenticated %}
            {% include "global/partials/_logged.html" %}
        {% else %}
            <div class="container">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <h2 class="text-center text-dark mt-5">Arcanjo DevOps</h2>
                        <div class="text-center mb-5 text-dark">Uma nova forma de trabalhar</div>
                        <div class="card my-5">
                            <form class="card-body cardbody-color p-lg-5" action="{{ form_action }}" method="POST">
                                {% csrf_token %}
            
                                <div class="text-center">
                                    <img src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295397__340.png"
                                        class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3" width="200px"
                                        alt="profile">
                                </div>
            
                                {% for field in form %}
                                    <div class="mb-3">
                                        <input type="{{ field.field.widget.input_type }}" class="form-control"
                                            id="{{ field.auto_id }}" name="{{ field.html_name }}"
                                            placeholder="{{ field.label }}">
            
                                        {% for error in field.errors %}
                                            <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% endfor %}
                                <br>
                                <div class="d-grid gap-2 px-5 mb-4 w-100">
                                    <button class="btn btn-primary" type="submit">Entrar</button>
                                </div>
            
                                <div id="emailHelp" class="form-text text-center mb-4 text-dark">Não tem registro? <a
                                    href="{% url 'arcanjo:register' %}" class="text-dark fw-bold"> Criar conta!</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

arcanjo/templates/contact/register.html
{% extends "global/login.html" %}

{% block content %}
<div class="form-wrapper">
    <br>
    {% if user.is_authenticated %}
        {% include "global/partials/_logged.html" %}
    {% else %}
        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <h2 class="text-center text-dark mt-5">Arcanjo DevOps</h2>
                    <div class="text-center mb-5 text-dark">Uma nova forma de trabalhar</div>
                        <div class="card my-5">
                            <form class="card-body cardbody-color p-lg-5" action="{{ form_action }}" method="POST">
                            {% csrf_token %}
        
                            <div class="text-center">
                                <img src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295397__340.png"
                                    class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3" width="200px"
                                    alt="profile">
                            </div>
        
                            {% for field in form %}
                                <div class="mb-3">
                                    <input type="{{ field.field.widget.input_type }}" class="form-control"
                                        id="{{ field.auto_id }}" name="{{ field.html_name }}"
                                        placeholder="{{ field.label }}">
        
                                    {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                                <div class="d-grid gap-2 px-5 mb-3 w-100">
                                    <button class="btn btn-primary" type="submit">Cadastrar</button>
                                </div>
                                <div id="emailHelp" class="form-text text-center text-dark"><a
                                    href="{% url 'arcanjo:login' %}" class="text-dark fw-bold"> Voltar</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

arcanjo/templates/contact/update-user.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        <br>
        <h2>Atualizar Usuário</h2>
        <br>

        <form action="{{ form_action }}" method="POST">
            {% csrf_token %}
        
            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        
                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>
        
            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </div>
            {% endif %}
            <br>
            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">Enviar</button>
            </div>
        </form>

    </div>
{% endblock content %}