core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('arcanjo.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls),
]

# Configuração para envio de arquivo para o servidor
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from services import views

app_name = 'services'

urlpatterns = [
    # PROJETOS
    path('project/', views.projects, name='projects'),
    path('project/<int:project_id>/detail/', views.project, name='project'),
    path('project/create/', views.create_project, name='create'),
    path('project/<int:project_id>/update/', views.update, name='update'),
    path('project/<int:contact_id>/delete/', views.delete, name='delete'),

    # DOCKER
    path('docker/', views.docker_list, name='docker_list'),

]

services/models.py
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=30)

    # Retorna o nome da categoria dentro de category no admin do django
    def __str__(self) -> str:
        return f'{self.name}'


class Status(models.Model):
    class Meta:
        verbose_name = 'Statu'
        verbose_name_plural = 'Status'

    name = models.CharField(max_length=10)

    # Retorna o nome da categoria dentro de category no admin do django
    def __str__(self) -> str:
        return f'{self.name}'


class Ambiente(models.Model):
    class Meta:
        verbose_name = 'Ambiente'
        verbose_name_plural = 'Ambientes'

    name = models.CharField(max_length=20)

    # Retorna o nome da categoria dentro de category no admin do django
    def __str__(self) -> str:
        return f'{self.name}'


class ServidorName(models.Model):
    class Meta:
        verbose_name = 'Nome do Servidor'
        verbose_name_plural = 'Nomes do Servidores'

    name = models.CharField(max_length=30)

    # Retorna o nome da categoria dentro de category no admin do django
    def __str__(self) -> str:
        return f'{self.name}'


class ServidorIp(models.Model):
    class Meta:
        verbose_name = 'IP do Servidor'
        verbose_name_plural = 'IPs do Servidor'

    name = models.CharField(max_length=30)

    # Retorna o nome da categoria dentro de category no admin do django
    def __str__(self) -> str:
        return f'{self.name}'


class Project(models.Model):
    project_name = models.CharField(max_length=50, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    status = models.ForeignKey(Status, on_delete=models.SET_NULL, blank=True, null=True)
    ambiente = models.ForeignKey(Ambiente, on_delete=models.SET_NULL, blank=True, null=True)
    technology = models.CharField(max_length=50)
    database = models.CharField(max_length=50)
    project_url = models.URLField(blank=True, null=True)
    server_name = models.ForeignKey(ServidorName, on_delete=models.SET_NULL, blank=True, null=True)
    server_ip = models.ForeignKey(ServidorIp, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.project_name

services/forms.py
from django import forms
from . import models


class ProjetoForm(forms.ModelForm):
    project_name = forms.CharField(label='Nome do Projeto')
    technology = forms.CharField(label='Tecnologia', required=False)
    database = forms.CharField(label='Banco de Dados', required=False)
    project_url = forms.URLField(label='URL do Projeto')
    

    class Meta:
        model = models.Project
        fields = ('project_name', 'category', 'ambiente', 'status', 'technology', 'database', 'project_url', 'server_name', 'server_ip',)

services/views/projetos_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from services.forms import ProjetoForm
from services.models import Project
import docker


def projects(request):
    projects = Project.objects.all()
    context = {'projects': projects,  'site_title': 'Projetos - '}
    return render(request, 'projects/projetos.html', context)


def project(request, project_id):
    '''retorna os dados de um contato via id (pk),
    caso o id não seja encontrado, ele retorna 404'''
    single_project = get_object_or_404(Project, pk=project_id)

    site_title = f'{single_project.project_name} - '
    context = {'project': single_project, 'site_title': site_title}

    # print(single_contact.query)
    return render(request, 'projects/projeto.html', context)


def create_project(request):
    form_action = reverse('services:create')

    if request.method == 'POST':
        form = ProjetoForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            print("Formulário é válido!")
            project = form.save()
            return redirect('services:update', project_id=project.pk)

        # print(contacts.query)
        return render(request, 'projects/create.html', context)

    context = {
        'form': ProjetoForm(),
        'form_action': form_action,

    }
    # print(contacts.query)
    return render(request, 'projects/create.html', context)


def update(request, project_id):
    project = get_object_or_404(
        Project, pk=project_id
    )
    form_action = reverse('services:update', args=(project_id,))

    if request.method == 'POST':
        form = ProjetoForm(request.POST, request.FILES, instance=project)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            print("Formulário é válido!")
            project = form.save()
            return redirect('services:update', project_id=project.pk)

        # print(project.query)
        return render(request, 'projects/create.html', context)

    context = {
        'form': ProjetoForm(instance=project),
        'form_action': form_action,

    }
    # print(contacts.query)
    return render(request, 'projects/create.html', context)


def delete(request, contact_id):
    project = get_object_or_404(
        Project, pk=contact_id
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        project.delete()
        return redirect('services:projects')

    return render(
        request,
        'projects/projeto.html',
        {
            'project': project,
            'confirmation': confirmation,
        }
    )


def docker_list(request):
    client = docker.from_env()
    containers = client.containers.list()

    container_info = []
    for container in containers:
        container_info.append({
            "Nome": container.name,
            "Status": container.status,
            "ID": container.short_id,
            "Imagem": container.image.tags[0] if container.image.tags else "",
            # "Comando": container.attrs['Config']['Cmd'] if 'Cmd' in container.attrs['Config'] else "",
            # "Portas": container.ports
        })

    context = {'containers': container_info}

    return render(request, 'projects/container_list.html', context)

services/templates/projects/container_list.html
{% extends "global/base.html" %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Projetos</h1>
    <a href="{% url 'services:create' %}" class="btn btn-primary">Novo Projeto</a>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <caption>Lista de Projetos</caption>
    <thead>
      <tr class="table-secondary">
        <th scope="col">Nome</th>
        <th scope="col">Status</th>
        <th scope="col">ID</th>
        <th scope="col">Imagem</th>
        {% comment %} <th scope="col">Comando</th>
        <th scope="col">Portas</th> {% endcomment %}
      </tr>
    </thead>
    <tbody>
      {% for container in containers %}
        <tr>
            <td> <a class="table-link" href="#">
              {{ container.Nome }}
            </td>
            <td>{{ container.Status }}</td>
            <td>{{ container.ID }}</td>
            <td>{{ container.Imagem }}</td>
            {% comment %} <td>{{ container.Comando }}</td>
            <td>{{ container.Portas }}</td> {% endcomment %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %} 

services/templates/projects/create.html
{% extends "global/base.html" %}

{% block content %}
    <div class="form-wrapper">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Adicionar Projeto</h1>
            <a href="{% url 'services:projects' %}" class="btn btn-primary">Voltar</a>
        </div>

        <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        
                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>

            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">Adicionar</button>
            </div>
            <br>
        </form>
    </div>
{% endblock content %}

services/templates/projects/projeto.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Nome do Projeto: {{ project.project_name }}</h1>
        <a href="{% url 'services:projects' %}" class="btn btn-primary">Voltar</a>
      </div>      

        {% comment %} <p><b>ID: </b> {{ project.id }}</p> {% endcomment %}
        <p><b>Categoria: </b> {{ project.category }}</p>
        <p><b>Status: </b> {{ project.status }}</p>
        <p><b>Ambiente: </b> {{ project.ambiente }}</p>
        <p><b>Tecnologia: </b> {{ project.technology }}</p>
        <p><b>Banco de Dados: </b> {{ project.database }}</p>
        <p><b>URL do Projeto: </b> <a href="{{ project.project_url }}">{{ project.project_url }}</a></p>
        <p><b>Nome do Servidor: </b> {{ project.server_name }}</p>
        <p><b>IP do Servidor: </b> {{ project.server_ip }}</p>

        <div class="d-grid gap-2 col-6 mx-auto">
          <a class="btn btn-primary" href="{% url 'services:update' project.id %}">Update</a></button>      
          <a class="btn btn-danger" href="{% url 'services:delete' project.id %}">Delete</a></button>  

          <form action="{% url 'services:delete' project.id %}" method="POST">
            {% csrf_token %}
            <br>
            {% if confirmation == 'no' %}
              <input type="hidden" name="confirmation" value="yes">
              <button class="btn btn-outline-warning d-grid gap-2 col-6 mx-auto" type="submit">Confirma?</button>
            {% endif %}
          </form>
          <br>
        </div>
    </div>
{% endblock content %}

services/templates/projects/projetos.html
{% extends "global/base.html" %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Projetos</h1>
    <a href="{% url 'services:create' %}" class="btn btn-primary">Novo Projeto</a>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <caption>Lista de Projetos</caption>
    <thead>
      <tr class="table-secondary">
        <th scope="col">Nome do Projeto</th>
        <th scope="col">Categoria</th>
        <th scope="col">Ambiente</th>
        <th scope="col">Status</th>
        <th scope="col">Tecnologia</th>
        <th scope="col">Banco de Dados</th>
        <th scope="col">URL do Projeto</th>
        <th scope="col">Nome do servidor</th>
        <th scope="col">IP do servidor</th>
      </tr>
    </thead>
    <tbody>
      {% for project in projects %}
        <tr>
          <td><a class="table-link" href="{% url 'services:project' project.id %}">
            {{ project.project_name }}
          </a>
          </td>
          <td class="table-cel">
            {{ project.category }}
          </td>
          <td class="table-cel">
            {{ project.ambiente }}
          </td>
          {% if project.status %}
            <td class="table-cel p-2 mb-1 bg-success text-white">{{ project.status }}</td> 
          {% else %}
            <td class="table-cel p-2 mb-1 bg-danger text-white">{{ project.status }}</td>
          {% endif %}
          
          <td class="table-cel">
            {{ project.technology }}
          </td>
          <td class="table-cel">
            {{ project.database }}
          </td>
          <td class="table-cel"><a href="{{ project.project_url }}">
            {{ project.project_url }}
          </td>
          <td class="table-cel">
            {{ project.server_name }}
          </td>
          <td class="table-cel">
            {{ project.server_ip }}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %} 